version: '3.8'
services:
  t1:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    ports:
      - '9101:9001'
    volumes:
      - oss-data-1:/data
    networks:
      - laf_shared_network

  t2:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - oss-data-2:/data
    networks:
      - laf_shared_network

  t3:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - oss-data-3:/data
    networks:
      - laf_shared_network

  t4:
    image: 'minio/minio:RELEASE.2022-08-13T21-54-44Z'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=${MINIO_VOLUMES}
      - MINIO_ETCD_ENDPOINTS=${MINIO_ETCD_ENDPOINTS}
      - MINIO_SKIP_CLIENT=yes
      - MINIO_REGION_NAME=cn-default
      - MINIO_DOMAIN=${MINIO_DOMAIN}
    command: server /data --console-address ":9001"
    volumes:
      - oss-data-4:/data
    networks:
      - laf_shared_network

  target-etcd:
    image: quay.io/coreos/etcd:v3.5.4
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=${MINIO_ETCD_ENDPOINTS}
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
    volumes:
      - etcd-data:/default.etcd
    ports:
      - 2379
      - 2380
    networks:
      - laf_shared_network

networks:
  laf_shared_network:
    external: true

volumes:
  oss-data-1:
  oss-data-2:
  oss-data-3:
  oss-data-4:
  etcd-data:
